"use client"
import { Suspense, useMemo, useState } from "react"
import { useSearchParams } from "next/navigation"
import { Header, Footer, ProductCard } from "../../components/storefront"
import { categories, products } from "../../data/products"

function ShopContent() { const params = useSearchParams(); const [category, setCategory] = useState(params.get("category") || "All"); const [sort, setSort] = useState("featured"); const [query, setQuery] = useState(params.get("q") || ""); const filtered = useMemo(() => { let result = products.filter((item) => (category === "All" || item.category === category) && `${item.name} ${item.description}`.toLowerCase().includes(query.toLowerCase())); if (sort === "price-low") result.sort((a,b) => a.price-b.price); if (sort === "price-high") result.sort((a,b) => b.price-a.price); if (sort === "name") result.sort((a,b) => a.name.localeCompare(b.name)); return result }, [category, sort, query]); return <main className="container page-main"><div className="page-intro"><p className="eyebrow">The collection</p><h1>Shop all</h1><p>Everyday pieces, thoughtfully considered.</p></div><div className="shop-toolbar"><div className="category-pills">{categories.map((item) => <button key={item} className={category === item ? "active" : ""} onClick={() => setCategory(item)}>{item}</button>)}</div><div className="shop-controls"><label className="inline-search"><span className="sr-only">Search products</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products"/></label><select value={sort} onChange={(event) => setSort(event.target.value)} aria-label="Sort products"><option value="featured">Featured</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option><option value="name">Name</option></select></div></div><p className="result-count">{filtered.length} {filtered.length === 1 ? "piece" : "pieces"}</p>{filtered.length ? <div className="product-grid">{filtered.map((product) => <ProductCard product={product} key={product.id}/>)}</div> : <div className="empty-state"><h2>No pieces found</h2><p>Try a different search or category.</p></div>}</main> }

export default function ShopPage() { return <><Header/><Suspense fallback={<main className="container page-main"><p>Loading collection...</p></main>}><ShopContent/></Suspense><Footer/></> }
