"use client"
import Link from "next/link"
import { notFound } from "next/navigation"
import { use, useState } from "react"
import { ArrowLeft, Check, ShoppingBag } from "lucide-react"
import { Header, Footer, ProductCard, Stars, QuantityControl } from "../../../components/storefront"
import { getProduct, getRelatedProducts, formatPrice, getProductImage } from "../../../data/products"
import { useCart } from "../../../context/cart-context"

export default function ProductPage({ params }) { const { id } = use(params); const product = getProduct(id); if (!product) return notFound(); const [option, setOption] = useState(product.options[0]); const [quantity, setQuantity] = useState(1); const [added, setAdded] = useState(false); const { addItem } = useCart(); function add() { addItem(product, option, quantity); setAdded(true); setTimeout(() => setAdded(false), 2200) } return <><Header/><main className="container page-main"><Link className="back-link" href="/shop"><ArrowLeft size={15}/> Back to shop</Link><div className="product-detail"><div className="detail-image"><img src={getProductImage(product, "1100")} alt={product.name}/></div><div className="detail-copy"><p className="eyebrow">{product.category}</p><h1>{product.name}</h1><div className="detail-price-row"><strong>{formatPrice(product.price)}</strong><Stars rating={product.rating}/></div><p className="detail-description">{product.description}</p><div className="option-group"><label>Choose {product.category === "Clothing" ? "size" : "color"}</label><div className="option-list">{product.options.map((item) => <button key={item} className={option === item ? "selected" : ""} onClick={() => setOption(item)}>{item}</button>)}</div></div><div className="purchase-row"><QuantityControl quantity={quantity} onChange={setQuantity}/><button className={`primary-button purchase-button ${added ? "is-added" : ""}`} onClick={add}>{added ? <><Check size={17}/> Added</> : <><ShoppingBag size={17}/> Add to cart</>}</button></div>{added && <p className="add-confirmation">Added to your cart. <Link href="/cart">View cart</Link></p>}<div className="detail-note"><Check size={16}/> Free shipping on orders over $100</div><div className="detail-note"><Check size={16}/> Easy returns within 30 days</div></div></div><section className="section related"><div className="section-heading"><div><p className="eyebrow">Keep exploring</p><h2>You may also like</h2></div></div><div className="product-grid">{getRelatedProducts(product).map((item) => <ProductCard key={item.id} product={item}/>)}</div></section></main><Footer/></> }
